name: expenses_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6  # current, no change needed
  font_awesome_flutter: ^10.7.0  # update from 10.6.0
  fl_chart: ^0.66.0  # or the latest version
  intl: ^0.19.0  # current, no change needed
  flutter_colorpicker: ^1.0.3  # current, no change needed
  uuid: ^4.3.3  # current, no change needed
  email_validator: ^2.1.17  # Add this line for email validation
  form_field_validator: ^1.1.0  # Add this line for form validation

  # Firebase packages should be updated together
  firebase_core: ^2.32.0  # update from 2.16.0
  cloud_firestore: ^4.9.2  # add this for Firestore
  firebase_auth: ^4.16.0  # add this if you need authentication
  # flutter_screenutil: ^5.9.0  # Add this line
  

  # State management packages
  bloc: ^8.1.2  # current, no change needed
  flutter_bloc: ^8.1.3  # current, no change needed
  equatable: ^2.0.5

  expense_repository:
    path: packages/expense_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/