// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeKmXnekRqDG8pjczytllpLMaKd6wYX60',
    appId: '1:280869591834:web:31c5f259903c10947b6aa3',
    messagingSenderId: '280869591834',
    projectId: 'expense-tracker-dbbe6',
    authDomain: 'expense-tracker-dbbe6.firebaseapp.com',
    storageBucket: 'expense-tracker-dbbe6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8vUiv4aYvDcI7CkIHwrI7VkhZCqvUhfo',
    appId: '1:280869591834:android:1267c0323c7eeb107b6aa3',
    messagingSenderId: '280869591834',
    projectId: 'expense-tracker-dbbe6',
    storageBucket: 'expense-tracker-dbbe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJC5txFCEfRbnravej0pwqF3QQ1P606Ac',
    appId: '1:280869591834:ios:6ab1e6e34df77d5f7b6aa3',
    messagingSenderId: '280869591834',
    projectId: 'expense-tracker-dbbe6',
    storageBucket: 'expense-tracker-dbbe6.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJC5txFCEfRbnravej0pwqF3QQ1P606Ac',
    appId: '1:280869591834:ios:6ab1e6e34df77d5f7b6aa3',
    messagingSenderId: '280869591834',
    projectId: 'expense-tracker-dbbe6',
    storageBucket: 'expense-tracker-dbbe6.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeKmXnekRqDG8pjczytllpLMaKd6wYX60',
    appId: '1:280869591834:web:a72a07a39d3906b87b6aa3',
    messagingSenderId: '280869591834',
    projectId: 'expense-tracker-dbbe6',
    authDomain: 'expense-tracker-dbbe6.firebaseapp.com',
    storageBucket: 'expense-tracker-dbbe6.firebasestorage.app',
  );
}
